// Master Contractor Preset Library
// Real-world average residential pricing (Labor & Material breakdown)

const PresetLibrary = [
  // ==========================================
  // SECTION 1: ELECTRICAL (TOP 100 RESIDENTIAL JOBS)
  // ==========================================
  // Outlets, Receptacles & Switches (1-20)
  { trade: 'electrical', category: 'outlets', desc: 'Standard 15A Tamper-Resistant Outlet Replace', qty: 1, unitPrice: 65, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'New Duplex Outlet Install (New Wire Run)', qty: 1, unitPrice: 185, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: '20A GFCI Outlet Installation (Bathroom/Kitchen)', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Outdoor Weatherproof GFCI Outlet with Cover', qty: 1, unitPrice: 145, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'USB-A/USB-C Dual Wall Outlet Install', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Floor Outlet Installation (Concrete/Wood)', qty: 1, unitPrice: 275, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Switched Outlet Conversion (Half-Hot)', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Single-Pole Light Switch Replacement', qty: 1, unitPrice: 55, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: '3-Way Switch Circuit Troubleshooting & Replacement', qty: 1, unitPrice: 120, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: '4-Way Light Switch Replacement', qty: 1, unitPrice: 135, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'LED Smart Dimmer Switch Install', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Occupancy / Motion Sensor Switch Installation', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Countdown Timer Switch Install (Bathroom Fan)', qty: 1, unitPrice: 90, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Smart Wi-Fi Switch System Setup (3-Pack)', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Childproof Outlet Cover Replacement (Whole House)', qty: 10, unitPrice: 120, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Ungrounded 2-Prong to 3-Prong GFCI Upgrade', qty: 1, unitPrice: 105, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Recessed TV Outlet with Cable Pass-Through', qty: 1, unitPrice: 165, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Under-Cabinet Plug Strip Installation', qty: 1, unitPrice: 195, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Commercial Grade Receptacle Upgrade (Heavy Usage)', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'electrical', category: 'outlets', desc: 'Replace Damaged Junction Box (In-Wall)', qty: 1, unitPrice: 125, type: 'Labor' },

  // Interior & Exterior Lighting (21-40)
  { trade: 'electrical', category: 'lighting', desc: '6" LED Recessed Can Light Install (New Construction)', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Retrofit LED Wafer Recessed Light Install (Old Work)', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Ceiling Fan Replacement (Standard Height)', qty: 1, unitPrice: 165, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Ceiling Fan Install with New Wiring & Fan Box', qty: 1, unitPrice: 320, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'High Ceiling Fan Install (12ft+ Scaffolding Required)', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Chandelier Replacement (Dining Room)', qty: 1, unitPrice: 195, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Heavy Crystal Chandelier Install (Reinforced Box)', qty: 1, unitPrice: 350, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Pendant Light Installation (Kitchen Island)', qty: 1, unitPrice: 135, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Under-Cabinet Hardwired LED Light Strip', qty: 1, unitPrice: 240, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Flush Mount Light Fixture Replacement', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Bathroom Vanity Light Fixture Replacement', qty: 1, unitPrice: 125, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Fluorescent Tube to LED Conversion (Garage)', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Track Lighting System Installation', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Exterior Sconce Fixture Replacement', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Motion-Activated Security Floodlight Install', qty: 1, unitPrice: 185, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Landscape Low-Voltage Transformer & Lights (6-Pack)', qty: 1, unitPrice: 580, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Soffit Exterior Recessed LED Lights (Per Light)', qty: 1, unitPrice: 130, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Post Light Replacement (Driveway/Yard)', qty: 1, unitPrice: 175, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Stairway Step Lighting Installation', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'electrical', category: 'lighting', desc: 'Accent Cove LED Strip Lighting', qty: 1, unitPrice: 210, type: 'Labor' },

  // Service Panels, Breakers & Service Upgrades (41-60)
  { trade: 'electrical', category: 'panels', desc: '200A Main Panel Upgrade (Meter Combo)', qty: 1, unitPrice: 2450, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: '100A Main Service Panel Replacement', qty: 1, unitPrice: 1650, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: '100A Subpanel Installation (Garage/Addition)', qty: 1, unitPrice: 1150, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: '60A Subpanel Installation (Shed/Workshop)', qty: 1, unitPrice: 850, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Single-Pole Circuit Breaker Replacement', qty: 1, unitPrice: 120, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Double-Pole Breaker Replacement (30A/40A/50A)', qty: 1, unitPrice: 160, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'AFCI Arc-Fault Breaker Upgrade (Per Breaker)', qty: 1, unitPrice: 145, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Whole-House Surge Protector Panel Install', qty: 1, unitPrice: 295, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Meter Socket Enclosure Replacement', qty: 1, unitPrice: 850, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Main Service Grounding Rod Installation (Pair)', qty: 1, unitPrice: 320, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Panel Directory Relabeling & Circuit Audit', qty: 1, unitPrice: 175, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Subpanel Feed Cable Replacement', qty: 1, unitPrice: 450, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Weatherhead & Riser Replacement', qty: 1, unitPrice: 680, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Generator Interlock Kit Installation', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Manual Transfer Switch Install (10-Circuit)', qty: 1, unitPrice: 950, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Automatic Transfer Switch Install (Whole House)', qty: 1, unitPrice: 1850, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Replace Corroded Bus Bar / Panel Tune-Up', qty: 1, unitPrice: 350, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Smart Electrical Panel Controller Install', qty: 1, unitPrice: 1250, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Service Entrance Cable Upgrade (SEU/SER)', qty: 1, unitPrice: 750, type: 'Labor' },
  { trade: 'electrical', category: 'panels', desc: 'Utility Disconnect / Reconnect Coordination Support', qty: 1, unitPrice: 250, type: 'Labor' },

  // EV Chargers, Heavy Appliances & 240V Circuits (61-80)
  { trade: 'electrical', category: 'heavy', desc: 'Level 2 EV Charger Outlet (NEMA 14-50, 50A)', qty: 1, unitPrice: 680, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Hardwired EV Charger Install (Tesla/ChargePoint)', qty: 1, unitPrice: 780, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Electric Dryer 240V Dedicated Outlet Run', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Electric Range / Oven 240V Outlet Circuit', qty: 1, unitPrice: 420, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Hot Tub / Spa Disconnect Panel & Hookup', qty: 1, unitPrice: 1150, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Central AC Dedicated 240V Line Run', qty: 1, unitPrice: 480, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Mini-Split Heat Pump Electrical Service Run', qty: 1, unitPrice: 520, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Tankless Water Heater 240V Dual Circuit Run', qty: 1, unitPrice: 890, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Electric Water Heater Re-Wire & Disconnect', qty: 1, unitPrice: 280, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Welder / Shop Equipment 240V Outlet Install', qty: 1, unitPrice: 410, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Sump Pump Dedicated 20A GFCI Circuit', qty: 1, unitPrice: 290, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Over-the-Range Microwave Dedicated Circuit', qty: 1, unitPrice: 310, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Garbage Disposal & Dishwasher Dual Circuit Run', qty: 1, unitPrice: 340, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Baseboard Electric Heater Installation', qty: 1, unitPrice: 260, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Electric Floor Radiant Heat Thermostat Wire', qty: 1, unitPrice: 320, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Attic Exhaust Fan Installation & Wiring', qty: 1, unitPrice: 350, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Bathroom Exhaust Fan / Light Combo Wiring', qty: 1, unitPrice: 290, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Pool Pump Motor Disconnect & Timer Box', qty: 1, unitPrice: 460, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'Sauna Electric Heater Dedicated Run', qty: 1, unitPrice: 720, type: 'Labor' },
  { trade: 'electrical', category: 'heavy', desc: 'RV 30A or 50A Hookup Outlet (Exterior)', qty: 1, unitPrice: 490, type: 'Labor' },

  // Rewiring, Safety, Low Voltage & Repairs (81-100)
  { trade: 'electrical', category: 'repairs', desc: 'Knob & Tube Wiring Remediation (Per Room)', qty: 1, unitPrice: 1250, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Aluminum Wiring AlumiConn Remediation (Per Outlet)', qty: 1, unitPrice: 45, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Whole House Smoke & CO Detector Replacement (6-Pack)', qty: 1, unitPrice: 280, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Hardwired Video Doorbell Install (Ring/Nest)', qty: 1, unitPrice: 125, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Doorbell Transformer & Chime Replacement', qty: 1, unitPrice: 145, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Cat6 Ethernet Cable Run (Per Drop)', qty: 1, unitPrice: 175, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Coaxial TV Cable Outlet Run', qty: 1, unitPrice: 135, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Thermostat Wire Run (C-Wire Adapter Install)', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Electrical Safety Inspection & Code Audit', qty: 1, unitPrice: 195, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Emergency Diagnostic & Circuit Tracing (1st Hour)', qty: 1, unitPrice: 150, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Underground Wire Fault Location & Repair', qty: 1, unitPrice: 480, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Fix Tripping Breaker / Dead Circuit Tracing', qty: 1, unitPrice: 165, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Replace Melted / Burned Receptacle Wire', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Splicing & Sealing Underground Cable (UF-B)', qty: 1, unitPrice: 210, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Whole House Re-Wire (1500 sq ft Home)', qty: 1, unitPrice: 8500, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Kitchen Remodel Electrical Rough-In', qty: 1, unitPrice: 2200, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Bathroom Remodel Electrical Rough-In', qty: 1, unitPrice: 1100, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Basement Finish Electrical Rough-In', qty: 1, unitPrice: 2800, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Home Addition Electrical Tie-In', qty: 1, unitPrice: 1900, type: 'Labor' },
  { trade: 'electrical', category: 'repairs', desc: 'Master Electrician Hourly Service Rate', qty: 1, unitPrice: 115, type: 'Labor' },

  // ==========================================
  // SECTION 2: FRAMING & DRYWALL (TOP 50 JOBS)
  // ==========================================
  { trade: 'framing_drywall', category: 'framing', desc: 'Partition Wall Framing (2x4 Lumber, Per Linear Ft)', qty: 10, unitPrice: 18, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Load-Bearing Wall Removal & LVL Beam Install', qty: 1, unitPrice: 2400, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Interior Door Rough Opening Framing', qty: 1, unitPrice: 180, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Exterior Door Opening Framing & Sheathing', qty: 1, unitPrice: 290, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Window Rough Opening Framing', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Basement Wall Furring Strips / Framing (Per Room)', qty: 1, unitPrice: 850, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Closet Framing Addition', qty: 1, unitPrice: 420, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Ceiling Joist Repair / Sistering (Per Joist)', qty: 1, unitPrice: 250, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Subfloor Board Replacement (3/4" OSB, 4x8 Sheet)', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'framing_drywall', category: 'framing', desc: 'Attic Access Hatch Framing & Trim', qty: 1, unitPrice: 210, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Drywall Hang & Finish (Level 4 Finish, Per Sheet)', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Drywall Patch Repair (Small Hole < 6")', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Drywall Patch Repair (Large Water Damage 4x4)', qty: 1, unitPrice: 280, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Ceiling Drywall Repair & Texture Match', qty: 1, unitPrice: 350, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Popcorn Ceiling Removal & Smooth Skim (Per Sq Ft)', qty: 200, unitPrice: 2.50, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Skim Coat Plaster Walls (Per Room)', qty: 1, unitPrice: 650, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Corner Bead Replacement & Taping', qty: 1, unitPrice: 120, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Greenboard Moisture-Resistant Drywall (Bathroom)', qty: 1, unitPrice: 90, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Cement Backer Board Install (Tile Substrate)', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Soundproof Drywall Install (QuietRock, Per Sheet)', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Knockdown / Orange Peel Texture Spray (Per Room)', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Stress Crack Repair & Re-Taping', qty: 1, unitPrice: 130, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Garage Firewall Drywall Install (5/8" Type X)', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Baseboard Molding Installation (Per Linear Ft)', qty: 50, unitPrice: 3.50, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Crown Molding Installation (Per Linear Ft)', qty: 40, unitPrice: 7.50, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Door Trim / Casing Installation (Per Door)', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Window Sill & Trim Casing Install', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Wainscoting / Beadboard Wall Panel Install', qty: 1, unitPrice: 480, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Interior Pre-Hung Door Installation', qty: 1, unitPrice: 185, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Exterior Entry Door Replacement', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Sliding Closet Door Track & Door Install', qty: 1, unitPrice: 165, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Pocket Door Frame & Hardware Install', qty: 1, unitPrice: 390, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'French Door Interior Installation', qty: 1, unitPrice: 420, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'R-13 Wall Fiberglass Batt Insulation (Per Sq Ft)', qty: 200, unitPrice: 1.20, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Blown-In Attic Insulation (R-38, Per Sq Ft)', qty: 500, unitPrice: 1.80, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Rigid Foam Board Insulation (Basement Walls)', qty: 1, unitPrice: 320, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Interior Wall Painting (2 Coats, Per Room)', qty: 1, unitPrice: 450, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Ceiling Painting (Per Room)', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Trim & Door Painting (Per Door)', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Cabinet Refinishing / Painting', qty: 1, unitPrice: 1200, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Wallpaper Removal (Per Room)', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Deck Board Replacement (Per Board)', qty: 1, unitPrice: 45, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Wood Deck Railing & Baluster Repair', qty: 1, unitPrice: 280, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Stair Tread & Riser Replacement', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Subfloor Squeak Repair (Screw Down Subfloor)', qty: 1, unitPrice: 160, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Drop Ceiling T-Bar & Tile Installation', qty: 1, unitPrice: 550, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Shed Wood Framing Repair', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Rotten Window Sill Wood Repair', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Fence Post Wood Replacement', qty: 1, unitPrice: 175, type: 'Labor' },
  { trade: 'framing_drywall', category: 'drywall', desc: 'Framing & Drywall Carpenter Hourly Rate', qty: 1, unitPrice: 75, type: 'Labor' },

  // ==========================================
  // SECTION 3: PLUMBING (TOP 50 JOBS)
  // ==========================================
  { trade: 'plumbing', category: 'fixtures', desc: 'Kitchen Faucet Replacement', qty: 1, unitPrice: 165, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Bathroom Sink Faucet Replacement', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Toilet Replacement & Wax Ring Seal', qty: 1, unitPrice: 185, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Toilet Flapper & Fill Valve Repair', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Garbage Disposal Replacement', qty: 1, unitPrice: 150, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Undermount Kitchen Sink Installation', qty: 1, unitPrice: 260, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Bathroom Vanity & Sink Install', qty: 1, unitPrice: 320, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Showerhead & Arm Replacement', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Shower Valve Cartridge Replacement', qty: 1, unitPrice: 165, type: 'Labor' },
  { trade: 'plumbing', category: 'fixtures', desc: 'Bathtub Drain & Overflow Replacement', qty: 1, unitPrice: 190, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'PEX Water Line Pipe Repair (Per Section)', qty: 1, unitPrice: 175, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Copper Pipe Leak Soldering Repair', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'P-Trap Under Sink Drain Line Replace', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Main Water Shutoff Valve Replacement', qty: 1, unitPrice: 280, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Outdoor Frost-Free Hose Bib Replacement', qty: 1, unitPrice: 195, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Angle Stop Valve Replacement (Under Sink)', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Washing Machine Hose & Valve Box Upgrade', qty: 1, unitPrice: 180, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Refrigerator Ice Maker Water Line Install', qty: 1, unitPrice: 160, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Gas Pipe Line Hookup for Appliance', qty: 1, unitPrice: 240, type: 'Labor' },
  { trade: 'plumbing', category: 'pipes', desc: 'Whole House PEX Re-Pipe (2 Bath Home)', qty: 1, unitPrice: 4800, type: 'Labor' },
  { trade: 'plumbing', category: 'drains', desc: 'Kitchen or Bathroom Drain Snaking (Unclog)', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'plumbing', category: 'drains', desc: 'Main Sewer Line Augering / Hydro-Jetting', qty: 1, unitPrice: 380, type: 'Labor' },
  { trade: 'plumbing', category: 'drains', desc: 'Sewer Camera Line Inspection', qty: 1, unitPrice: 250, type: 'Labor' },
  { trade: 'plumbing', category: 'drains', desc: 'Clogged Toilet Mechanical Snake Clearing', qty: 1, unitPrice: 115, type: 'Labor' },
  { trade: 'plumbing', category: 'drains', desc: 'Shower Drain Hair Clog Clearing', qty: 1, unitPrice: 125, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: '50-Gallon Gas Water Heater Replacement', qty: 1, unitPrice: 1450, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: '50-Gallon Electric Water Heater Replacement', qty: 1, unitPrice: 1250, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Tankless Gas Water Heater Installation', qty: 1, unitPrice: 2800, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Water Heater Thermal Expansion Tank Install', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Water Heater Drain & Flush Tune-Up', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Water Heater Heating Element Replace (Electric)', qty: 1, unitPrice: 185, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Water Heater Thermocouple Replacement', qty: 1, unitPrice: 150, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'PRV (Pressure Reducing Valve) Replace', qty: 1, unitPrice: 290, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Sump Pump Replacement & Check Valve', qty: 1, unitPrice: 340, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Battery Backup Sump Pump System Install', qty: 1, unitPrice: 680, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Water Softener Loop Installation', qty: 1, unitPrice: 450, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Whole House Water Filtration System Install', qty: 1, unitPrice: 750, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Reverse Osmosis Under-Sink System Install', qty: 1, unitPrice: 260, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Sewage Ejector Pump Replacement', qty: 1, unitPrice: 620, type: 'Labor' },
  { trade: 'plumbing', category: 'water_heaters', desc: 'Bidet Toilet Seat Installation & T-Valve', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Tub Spout Replacement with Diverter', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Dishwasher Drain Line Hookup & Air Gap', qty: 1, unitPrice: 130, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Gas Leak Diagnostic & Bubble Test', qty: 1, unitPrice: 180, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Fix Leaking Shower Pan Drain Gasket', qty: 1, unitPrice: 210, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Cleanout Plug Replacement & Cap Seal', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Well Pump Pressure Switch Replacement', qty: 1, unitPrice: 240, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Backflow Preventer Testing & Repair', qty: 1, unitPrice: 190, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Pipe Insulation Sleeve Installation (20ft)', qty: 1, unitPrice: 120, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Emergency Plumbing Diagnostic Fee', qty: 1, unitPrice: 150, type: 'Labor' },
  { trade: 'plumbing', category: 'repairs', desc: 'Journeyman Plumber Hourly Service Rate', qty: 1, unitPrice: 95, type: 'Labor' },

  // ==========================================
  // SECTION 4: GENERIC HANDYMAN & REPAIRS (TOP 50 JOBS)
  // ==========================================
  { trade: 'handyman', category: 'assembly', desc: 'TV Wall Mount Installation (Up to 65")', qty: 1, unitPrice: 125, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Large TV Wall Mount (75"+ onto Masonry/Fireplace)', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'IKEA / Flat-Pack Furniture Assembly (Per Hour)', qty: 2, unitPrice: 65, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Outdoor Grill / Patio Furniture Assembly', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Fitness Equipment Assembly (Treadmill/Elliptical)', qty: 1, unitPrice: 160, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Curtain Rod & Drapery Hanging (Per Window)', qty: 1, unitPrice: 55, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Blind & Shade Installation (Per Window)', qty: 1, unitPrice: 45, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Heavy Mirror / Artwork Wall Mounting', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Floating Wall Shelf Installation (Set of 3)', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'handyman', category: 'assembly', desc: 'Closet Organizer System Installation', qty: 1, unitPrice: 320, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Door Hardware / Knob & Deadbolt Replacement', qty: 1, unitPrice: 65, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Smart Door Lock Installation (August/Schlage)', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Door Weatherstripping Replacement', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Screen Door / Storm Door Installation', qty: 1, unitPrice: 175, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Window Screen Mesh Replacement (Per Screen)', qty: 1, unitPrice: 40, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Adjust Misaligned Cabinet Doors / Drawers', qty: 1, unitPrice: 80, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Sliding Door Roller & Track Repair', qty: 1, unitPrice: 145, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Pet Door Installation (In Wood Door)', qty: 1, unitPrice: 160, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Door Hinge Squeak & Realignment Tune-Up', qty: 1, unitPrice: 70, type: 'Labor' },
  { trade: 'handyman', category: 'doors_windows', desc: 'Mailbox & Post Replacement', qty: 1, unitPrice: 150, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Caulk Bathtub / Shower Enclosure (Remove & Recaulk)', qty: 1, unitPrice: 125, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Caulk Kitchen Countertop Splash Guard', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Grout Repair & Tile Sealing (Bathroom)', qty: 1, unitPrice: 195, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Replace Broken Floor Tile (Per Tile)', qty: 1, unitPrice: 90, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Pressure Wash Driveway & Sidewalk', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Pressure Wash Deck / Patio', qty: 1, unitPrice: 180, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Gutter Cleaning (Single Story Home)', qty: 1, unitPrice: 140, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Gutter Guard Installation (Per Linear Ft)', qty: 100, unitPrice: 4.50, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Gutter Downspout Repair & Extension', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Attic Pull-Down Ladder Replacement', qty: 1, unitPrice: 340, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Garage Door Opener Installation', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Garage Door Weather Seal Bottom Strip Replace', qty: 1, unitPrice: 90, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Garage Storage Rack Ceiling Installation', qty: 1, unitPrice: 180, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Hang Grab Bars in Shower (ADA Safety)', qty: 2, unitPrice: 110, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Fence Picket Board Repair (Per Section)', qty: 1, unitPrice: 120, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Fence Gate Latch & Sag Adjustment', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Cabinet Drawer Slide Hardware Replacement', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Cabinet Handles & Knobs Install (10 Pack)', qty: 1, unitPrice: 85, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Dryer Vent Duct Lint Cleaning', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Roof Ridge Cap Shingle Patch Repair', qty: 1, unitPrice: 280, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Soffit / Fascia Board Wood Rot Patch', qty: 1, unitPrice: 240, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Siding Vinyl Panel Replacement (Per Panel)', qty: 1, unitPrice: 160, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Window A/C Unit Seasonal Installation', qty: 1, unitPrice: 75, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Weatherization Seal Home (Doors & Windows)', qty: 1, unitPrice: 220, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Childproofing Home Package (Gates, Latches)', qty: 1, unitPrice: 195, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Light Trash Haul / Yard Waste Removal', qty: 1, unitPrice: 150, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Pipelining Insulation Wrap (Basement)', qty: 1, unitPrice: 110, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Hanging Outdoor Holiday Lights (Standard House)', qty: 1, unitPrice: 250, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'Handyman Minimum Service Call Fee', qty: 1, unitPrice: 95, type: 'Labor' },
  { trade: 'handyman', category: 'general', desc: 'General Handyman Hourly Labor Rate', qty: 1, unitPrice: 65, type: 'Labor' }
];